language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: CS=1
      env: ANALYSE=0

    - php: 7.1
      env: CS=0
      env: ANALYSE=0

    - php: 7.2
      env: CS=0
      env: ANALYSE=1

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - composer test
  - if [[ $CS = 1 ]]; then composer cs-check; fi
  - if [[ $ANALYSE = 1 ]]; then composer analyse; fi

notifications:
  email: false
